# Generated by Django 5.0.3 on 2024-03-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('lien_insta', models.CharField(max_length=64)),
                ('lien_facebook', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=64)),
                ('order_on_home', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=64)),
                ('salaire', models.IntegerField()),
                ('wilaya', models.CharField(max_length=64)),
                ('commune', models.CharField(max_length=64)),
                ('adresse_complete', models.TextField()),
                ('mode_de_livraison', models.CharField(max_length=64)),
                ('date_heure_envoi', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('nom_complet', models.CharField(max_length=64)),
                ('prix_principal', models.IntegerField()),
                ('image', models.CharField(max_length=64)),
                ('nb_commandes', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Mensualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualites', to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_detail', models.CharField(max_length=64)),
                ('information', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Description_Paragraphe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraphe', models.TextField()),
                ('order', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Produit_Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.commande')),
                ('prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mensualite')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=64)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='api.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.sous_categorie'),
        ),
    ]
