# Generated by Django 5.0.3 on 2024-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commande_salaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='Salaire',
            new_name='salaire',
        ),
        migrations.AlterField(
            model_name='produit',
            name='nb_commandes',
            field=models.IntegerField(default=0),
        ),
    ]
