# Generated by Django 5.0.3 on 2024-03-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_produit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualite',
            name='remboursement_mois',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mensualite',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
