# Generated by Django 5.0.3 on 2024-03-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_salaire_commande_salaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit_commande',
            name='quantite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
