# Generated by Django 5.0.3 on 2024-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mensualite_remboursement_mois_alter_mensualite_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit_commande',
            name='prix',
        ),
        migrations.AddField(
            model_name='produit_commande',
            name='duree_mois',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit_commande',
            name='prix_mois',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_principal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit_commande',
            name='produit',
            field=models.CharField(max_length=64),
        ),
    ]
