# Generated by Django 5.0.3 on 2024-03-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_produit_commande_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualite',
            name='order',
            field=models.IntegerField(),
        ),
    ]
