# Generated by Django 5.0.3 on 2024-03-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mensualite_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description_paragraphe',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='order',
            field=models.IntegerField(),
        ),
    ]
