# Generated by Django 5.0.3 on 2024-03-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_description_paragraphe_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_principal',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
    ]
